### ISSUE TITLE
Support LAST_UPDATED on xxx_LOGICAL_RESOURCES tables

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#2011] opened 2021-03-02 21:04 UTC
Currently the LAST_UPDATED field exists only on each xxx_RESOURCES table. This requires this table to be joined every time. This join can be eliminated if LAST_UPDATED is denormalized and also stored at the xxx_LOGICAL_RESOURCES level where it represents the most recent change that has occurred for a given resource.

It makes sense to fold this into the same release as issue #1958 which adds IS_DELETED to the xxx_LOGICAL_RESOURCES table for the same reason.

This issue also addresses the defect uncovered related to DROP PRIMARY KEY for PostgreSQL.

**Comment by lmsurpre** [comment] 2021-03-04 12:50
At first I thought this was a duplicate of #1923 but I guess 1923 is just for the whole-system "LOGICAL_RESOURCES" whereas this one is for the resource-specific xxx_LOGICAL_RESOURCES.  Can you please confirm that BOTH of these were addressed in https://github.com/IBM/FHIR/pull/2013
If not, does it make sense to try squeezing this one in?

**Closed** 2021-03-04 12:56 UTC
Labels: P1, bug, schema-change
