### ISSUE TITLE
search index not updating properly when a versioned reference is updated to a different versioned reference

### ISSUE THREAD

**Issue by kmbarton423** [IBM/FHIR#3446] opened 2022-03-09 17:13 UTC
Created a Patient, deleted it, then created it again (current version is 3)
Created a Condition with subject set to Patient/<patient.resource.id>/_history/1
Did a search for this Condition with _include of the subject:
   .../Condition?_id=<condition.resource.id>&_include=Condition:subject
Received the expected response of the Condition along with Patient/<patient.resource.id>/_history/1
Updated the Condition subject to Patient/<patient.resource.id>/_history/2
Repeated the search above
Expected to receive only the Condition resource since the subject versioned reference is a deleted Patient.
Instead, received the previous search response of the Condition along with Patient/<patient.resource.id>/1

Working on the latest version of main.

**Comment by kmbarton423** [comment] 2022-03-09 17:16
Per discussion with Robin ... added label, estimate, and release

**Comment by punktilious** [comment] 2022-03-14 12:01
It appears as though the reference version field is not included in the fingerprint and so the parameter update is being skipped because the ingestion code thinks that nothing has changed.

**Comment by tbieste** [comment] 2022-03-21 19:44
I verified that the behavior described in this issue is now working as expected.
In this case, while testing, after updating the Condition to point to (deleted) version 2 of the Patient, the Patient is no longer returned as "included", which matches the expected behavior.
Marking as closed.

**Closed by tbieste** 2022-03-21 19:44 UTC
Labels: bug, P1
