### ISSUE TITLE
_sort query param on DocumentReference search causes duplicate resource ids to be returned

### ISSUE THREAD

**Issue by ajdorenk** [IBM/FHIR#440] opened 2019-11-22 21:17 UTC
**Describe the bug**
As part of our application, we routinely search for DocumentReference resources. After adding this search param: `&_sort:desc=created` to our DocumentReference searches, we've noticed that out of all the resources returned, there will be resources that have duplicate resource ids. We've noticed up to 8 duplicate DocumentReference resource ids when we're done paging for all resources. We haven't been able to determine whether just the resource id is being duplicated or if the entire DocumentReference resources are being duplicated. Additionally, we haven't been able to determine whether this problem presents itself when just making a request for a single page. All we know is that this problem occurs for sure when making multiple requests to get all the pages of a DocumentReference search. 

**To Reproduce**
1. Do a search for DocumentReference resources using this as a search param `&_sort:desc=created`
2. Request all the resources from all the pages and then check for duplicate resource ids and/or entirely duplicated resources.

**Expected behavior**
We would expect that the DocumentReference resource ids would all be unique, and that using the _sort search param would not cause duplicate resource ids to be returned.

**Comment by prb112** [comment] 2019-11-22 21:19
@ajdorenk this is most likely a duplicate of https://github.com/IBM/FHIR/issues/265

**Comment by prb112** [comment] 2019-11-22 21:20
We'll look at the specific example.

**Comment by prb112** [comment] 2019-11-22 21:34
Chatted with @ajdorenk - the issue is with an older version.  Recently, the issue is fixed in #265 which was migrated from internal repo/issues (related to duplicate resources)

**Closed** 2019-11-22 21:34 UTC
Labels: bug
