### ISSUE TITLE
fhir-persistence-schema doesn't behave as expected. 

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1858] opened 2021-01-08 20:40 UTC
**Describe the bug**
1. ibm-fhir-schematool doesn't specify the target schema to be granted permissions for oauth/jbatch.
2. ibm-fhir-schematool doesn't specify the target schema to be dropped for oauth/jbatch or fhirdata.
3. fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java doesn't allow schema names to be set.

**To Reproduce**

1. Create a postgres db
```
docker run -itd \
    --rm --name postgresfhir \
    --shm-size=256m \
    --sysctl net.core.somaxconn=256 \
    --sysctl net.ipv4.tcp_syncookies=0 \
    --hostname db \
    -e POSTGRES_USER=postgres \
    -e POSTGRES_PASSWORD=change-password \
    -e PGDATA=/var/lib/postgresql/data/pgdata \
    -e POSTGRES_DB=fhirdb \
    -p 5432:5432 \
    --privileged \
    -v "$PWD/my-postgres.conf":/etc/postgresql/postgresql.conf \
    postgres:12.5 postgres -c 'config_file=/etc/postgresql/postgresql.conf'
```

Be sure max_locks_per_transaction = 10000 is set.

2. Run the following
- `docker run --rm  --env ENV_TOOL_INPUT=$(cat persistence-onboard-example.json | base64) ibm-fhir-schematool:latest`
- `docker run --rm  --env ENV_TOOL_INPUT=$(cat persistence-offboard-example.json | base64) ibm-fhir-schematool:latest`

**Expected behavior**
The grant should work properly and the drop-schema should be dropped.

**Additional context**
n/a

**Comment by lmsurpre** [comment] 2021-01-11 19:39
is this a duplicate of https://github.com/IBM/FHIR/issues/1167 ?

**Comment by prb112** [comment] 2021-01-20 16:19
related, yet slightly different, as it fixes a specific issue.

**Closed** 2021-01-22 19:58 UTC
Labels: bug

**Comment by holger-stenzhorn** [comment] 2021-01-24 10:46
Just for curiosity... Is this also related to #1795?

**Comment by prb112** [comment] 2021-01-26 15:12
Yes - you are correct.
