### ISSUE TITLE
Potential to improve performance using _lastUpdated and identity columns directly

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1331] opened 2020-07-10 14:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently _lastUpdated and identity filters are treated like ordinary search properties in the query builder, forcing a join against the correspond str_values or date_values tables.

These attributes also currently exist on the <resourceType>_LOGICAL_RESOURCES and <resourceType>_RESOURCES tables. By writing the filter predicates against these columns should eliminate a join and potentially simplify the execution plan resulting in better performance.

A new index on the resources.last_updated field would be required.

**Describe the solution you'd like**
Investigate if updating search queries to use the logical resource/resource columns provides a better (and more stable) execution plan.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JohnTimm** [comment] 2020-07-10 14:35
Is this a duplicate of: https://github.com/IBM/FHIR/issues/255 ?

**Comment by JohnTimm** [comment] 2020-07-10 15:57
@prb112 As part of #255, do you know if there was an index created per Robin's description on this issue?

**Comment by prb112** [comment] 2020-07-10 16:03
I am not a 100% sure, that's why I left my comment in our side chat.  It's definitely worthy of a refactor as well.

**Closed** 2020-07-31 12:40 UTC
Labels: enhancement, performance
