### ISSUE TITLE
Liberty openapi processor complains of invalid UTF-8 on windows

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#902] opened 2020-04-07 02:13 UTC
**Describe the bug**
I noticed the following output from our windows e2e tests:
```
[4/7/20, 0:19:00:538 UTC] 00000020 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "com.fasterxml.jackson.core.JsonParseException: Invalid UTF-8 start byte 0x93
 at [Source: (byte[])"
{
    "openapi": "3.0.0",
    "info": {
        "title": "Simplified FHIR API",
        "description": "A simplified version of the HL7 FHIR API",
        "version": "4.0.1"
    },
    "servers": [
        {
            "url": "/fhir-server/api/v4"
        }
    ],
    "x-ibm-configuration": {
        "gateway": "datapower-api-gateway",
        "type": "rest",
        "phase": "realized",
        "enforced": true,
        "testable": true,
        "cors": {
            "enab"[truncated 7442084 bytes]; line: 54107, column: 370] com.ibm.ws.microprofile.openapi.impl.parser.OpenAPIV3Parser 206" at ffdc_20.04.07_00.19.00.0.log
[4/7/20, 0:19:00:538 UTC] 00000020 com.ibm.ws.microprofile.openapi.ApplicationProcessor         E CWWKO1659E: Failed to parse the OpenAPI document for application: fhir-openapi.
```

I checked the file and its complaining about stylized quotes that are included in the description of CarePlan.Activity.outcomeReference:
`a reference to a “request” resource`

That same character appears in over 100 different spots in the profiles-resources.json in this project, so we definitely need to handle it correctly (vs. modifying the source data).

**To Reproduce**
Run the e2e-windows test

**Expected behavior**
No error from parsing the openapi.json

**Additional context**
I double-check that we specify UTF-8 in both the Reader and the Writer being used from `FHIROpenApiGenerator` and so I'm really not sure how this character slips through...

- [Link to the Workflow](https://github.com/IBM/FHIR/runs/566334425?check_suite_focus=true)
- [Error at Code](https://github.com/OpenLiberty/open-liberty/blob/7c6d104f0fb8063f9183f4d839ed0dce7d3496e5/dev/com.ibm.ws.microprofile.openapi/src/com/ibm/ws/microprofile/openapi/impl/parser/OpenAPIV3Parser.java#L203);

**Comment by prb112** [comment] 2020-04-07 11:53
I can work on this one... I'm pretty sure I know where the root cause is.  We might have to specify UTF8 in jvm.options

**Comment by prb112** [comment] 2020-04-07 23:51
I transformed the offending Unicode characters that are not UTF-8 compliant. 
https://github.com/IBM/FHIR/pull/905/files

I dug into the Liberty code, and there are not good ways to override the encoding from a openapi perspective.

**Comment by prb112** [comment] 2020-04-08 12:22
PR https://github.com/IBM/FHIR/pull/908 
- Added warning to detect issues with OpenAPI codeset
- Updated the Code with hints on resolving future issues

**Closed** 2020-04-08 13:08 UTC
Labels: bug, os:windows
