### ISSUE TITLE
Replace legacy JDBC id caches with 1366 implementation

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1637] opened 2020-10-28 17:44 UTC
Feature 1366 introduced a new cache mechanism for handling id lookups related to parameter names, resource types and code systems.

There are still uses of the old caches in the JDBC persistence layer. These uses should be migrated to the new caches so we only have one cache implementation.

**Comment by prb112** [comment] 2022-02-16 00:37
Duplicate of [2901](https://github.com/IBM/FHIR/issues/2901)

**Closed by prb112** 2022-02-16 00:37 UTC
Labels: enhancement
