### ISSUE TITLE
value-quantity search and sort don't work as expected

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#410] opened 2019-11-14 04:01 UTC
Create several observations , some of them with value-quantity(125.0mmHg), and some of them without value-quantity, the following search tests got wrong results: 
(1) (verified that this was actually fixed in PR369) search observations equal to any value, less than any value or greater than any value always returns all the observations(with or without value-quantity). e.g: 
        queryParam("value-quantity", "25.0||mmHg")
        queryParam("value-quantity", "le12.0||mmHg")
        queryParam("value-quantity", "gt823.0||mmHg")
 (2) sorting by value-quantity doesn't work, the returned entries are not sorted at all
       queryParam("_sort:asc", "component-value-quantity")

**Comment by lmsurpre** [comment] 2019-11-14 13:38
Where are the units?  Are they coded units (code field) or display units (unit field)?

**Comment by lmsurpre** [comment] 2019-11-14 13:59
see https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=19597 for why that matters.  currently we only index the unit field if the coded units are missing.

**Comment by lmsurpre** [comment] 2019-11-14 14:39
I chatted with Albert on this one and I think its a duplicate of https://github.com/IBM/FHIR/issues/370 ...albert is going to sync with master to confirm.

**Comment by albertwang-ibm** [comment] 2019-11-14 16:28
after sync with master, update the server config and test again, the first issue is gone, but the 1nd issue is not fixed.

**Comment by lmsurpre** [comment] 2019-11-15 04:49
I split the sort issue into #418.

Also, we merged pull request #416 to  address the potential issue wrt https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=19597.

Based on those, I'm moving this to under review...please re-open if you think we need any further changes on this one.

**Closed** 2019-11-21 18:20 UTC
Labels: bug
