### ISSUE TITLE
schema name case normalization is not working as expected

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1971] opened 2021-02-18 23:25 UTC
**Describe the bug**
In the fix for https://github.com/IBM/FHIR/issues/1783 we started normalizing schema names to upper case.

Unfortunately, for users that have lowercase characters in their schema name, we are not properly updating the FHIR_ADMIN.VERSION_HISTORY table.

Specifically, instead of updating the existing objects in the table, we seem to be creating a new entry in the table (this one with an upper-case schema name).

**To Reproduce**
1. Create and deploy our schema using a version of fhir-persistence-schema prior to https://github.com/IBM/FHIR/pull/1782 (which I believe was released in 4.5.1) and pass a lower-case schema name (e.g. "fhirdata")
2. Run the `--update-schema` action using the latest fhir-persistence-schema project

`select * from fhir_admin.version_history` and note that *_Resource_Token_Refs tables now have two entries:
* one version for schemaname "fhirdata"
* version 8 for schemaname "FHIRDATA"

Also note that if the `--update-schema` is executed a second time, it now fails with errors like:
```
WARNING ls.pool.PoolConnectionProvider Rolling back transaction
2021-02-18 15:37:13.495 wh-cmsiop-cthon-fhir-update-schema-5rhqr fhir-schematool SEVERE 00000017  SEVERE .fhir.task.core.impl.TaskGroup GROUP:FHIRDATA.COVERAGEELIGIBILITYRESPONSE_RESOURCE_TABLE_GROUP:0
2021-02-18 15:37:13.495 wh-cmsiop-cthon-fhir-update-schema-5rhqr fhir-schematool ERROR 
org.postgresql.util.PSQLException: ERROR: index "idx_coverageeligibilityresponse_resource_token_refs_tvlr" does not exist
com.ibm.fhir.database.utils.api.UndefinedNameException: org.postgresql.util.PSQLException: ERROR: index "idx_coverageeligibilityresponse_resource_token_refs_tvlr" does not exist
	at com.ibm.fhir.database.utils.postgres.PostgresTranslator.translate(PostgresTranslator.java:100)
	at com.ibm.fhir.database.utils.common.DropIndex.run(DropIndex.java:46)
	at com.ibm.fhir.database.utils.common.CommonDatabaseAdapter.runStatement(CommonDatabaseAdapter.java:459)
	at com.ibm.fhir.database.utils.postgres.PostgresAdapter.runStatement(PostgresAdapter.java:266)
	at com.ibm.fhir.database.utils.model.Table$$Lambda$116/00000000D00089A0.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:668)
	at com.ibm.fhir.database.utils.model.Table.apply(Table.java:148)
	at com.ibm.fhir.database.utils.model.BaseObject.applyVersion(BaseObject.java:263)
	at com.ibm.fhir.database.utils.model.ObjectGroup.applyVersion(ObjectGroup.java:67)
	at com.ibm.fhir.database.utils.model.BaseObject.applyTx(BaseObject.java:214)
	at com.ibm.fhir.database.utils.model.BaseObject.lambda$collect$0(BaseObject.java:201)
	at com.ibm.fhir.database.utils.model.BaseObject$$Lambda$109/000000004053A600.run(Unknown Source)
	at com.ibm.fhir.task.core.impl.TaskGroup.runTask(TaskGroup.java:137)
	at com.ibm.fhir.task.core.impl.TaskGroup.lambda$runTask$0(TaskGroup.java:129)
	at com.ibm.fhir.task.core.impl.TaskGroup$$Lambda$110/000000004053ACB0.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: org.postgresql.util.PSQLException: ERROR: index "idx_coverageeligibilityresponse_resource_token_refs_tvlr" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:258)
	at com.ibm.fhir.database.utils.common.DropIndex.run(DropIndex.java:42)
	... 19 more
```

**Expected behavior**
1. `--update-schema` should be idempotent; no exceptions if there's nothing that needs migrating
2. VERSION_HISTORY table should only have a single entry for each schema object in the database

**Additional context**
[data-1613683565688.csv.txt](https://github.com/IBM/FHIR/files/6006512/data-1613683565688.csv.txt)

**Comment by d0roppe** [comment] 2021-02-28 13:39
Unable to reproduce the reported problem with the fix.  Closing the issue.

**Closed by d0roppe** 2021-02-28 13:39 UTC
Labels: P1, bug
