### ISSUE TITLE
Bootstrapping of Derby database should be driven by configuration

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1408] opened 2020-08-08 16:05 UTC
**Is your feature request related to a problem? Please describe.**
The server bootstraps 4 Derby database schemas on initial startup:

            bootstrapFhirDb(utx, "default", "default", ds);
            bootstrapFhirDb(utx, "tenant1", "profile", ds);
            bootstrapFhirDb(utx, "tenant1", "reference", ds);
            bootstrapFhirDb(utx, "tenant1", "study1", ds);

This aligns with the initial configuration, and is intended to make the FHIR server easy to get up an running.

**Describe the solution you'd like**
Drive the bootstrapping from the fhir-server-config configuration. The bootstrap can then be skipped where a Derby database isn't required (e.g. in production instances).

**Describe alternatives you've considered**
Disable bootstrapping entirely and require database schemas to be provisioned before the server starts.

**Additional context**
N/A

**Comment by lmsurpre** [comment] 2021-01-26 15:58
I would vote to remove all bootsrapping code from the server and move it into a different shell script.  Then, for our docker image, we could run that to bootstrap derby (conditionally, based on some argument/config)

**Comment by lmsurpre** [comment] 2021-02-23 19:20
Currently I'm thinking to keep this simple.  We would *only* support bootstrapping of the default tenant's default datasource.
For our FHIR CI's multi-tenant tests, we'd need to do something special if we intend to continue supporting the 3 datastores for tenant1.

**Comment by tbieste** [comment] 2021-02-23 22:34
Wanted to get thoughts on the ENVVARs to use for the new script to be called by the fhir-server Dockerfile.

|Ibm-fhir-schematool |property	Ibm-fhir-schematool Purpose|	ENVVAR in ibm-fhir-server script|
|---------|-----------------|-----|
| |	|	DB_BOOTSTRAP: Whether to bootstrap DB. [true/false] |
|tool.behavior|	Switches from the Onboarding BEHAVIOR to Offboarding BEHAVIOR flow: [onboard/offboard/debug/custom].|	N/A|
|db.type|	The database type - [postgresql/db2]|	DB_TYPE: The DB type. [db2/derby/postgresql] |
|db.host|	The database server hostname|	DB_HOST: The DB host.|
|db.port|	The database server port|	DB_PORT: The DB port.|
|db.database|	The name of the database|	DB_DATABASE: The DB name.|
|user|	A username with connect and admin permissions on the target database|	DB_ADMIN_USER: The DB user.|
|password|	The user password for connecting to the database|	DB_ADMIN_PASSWORD: The DB password.|
|sslConnection|	true or anything else, true triggers JDBC to use ssl, an example --prop sslConnection=true (db2)|	NA (Duplicate of DB_SSL)|
|ssl|	true or anything else, true triggers JDBC to use ssl, an example --prop ssl=true (postgres)|	DB_SSL: [true/false]|
|tenant.key|	the tenant key is a generated key, or used to set a specific value|	DB_DB2_TENANT_KEY: [true/false]|
|tenant.name|	the tenant name is typically default|	N/A (default to default)|
|schema.name.oauth|	uses the default or custom|	N/A (default to FHIR_OAUTH)|
|schema.name.fhir|	defaults to fhirdata|	N/A (default to FHIRDATA)|
|schema.name.batch|	uses the default or custom|	N/A (default to FHIR_JBATCH)|
|grant.to|	grants access to a specific user (which is going to run the application)|	DB_GRANT_TO: User to grant access to schema (optional)|
|sslmode|	For Postgres, you can set verify-full|	N/A (default to verify-full)|
|sslrootcert|	For Postgres, you must set as /opt/schematool/workarea/db.cert|	N/A (default to /opt/fhir-server/workarea/db.cert)|
|db.cert|	For Postgres, you must set as a base64 encoding of the certificate|	DB_SSL_ROOT_CERT: base64 of certificate|

Checking if any aren't needed, or any marked N/A really are needed.

**Comment by lmsurpre** [comment] 2021-02-23 22:53
One thing that is supported by the keycloak image, which I kind of like, is the ability to set the DB_ADMIN_USER and DB_ADMIN_PASSWORD via mounted files.

specifically, they support both the env var and file location variants:
```
DB_USER: Specify user to use to authenticate to the database (optional, default is ``).
DB_USER_FILE: Specify user to authenticate to the database via file input (alternative to DB_USER).
DB_PASSWORD: Specify user's password to use to authenticate to the database (optional, default is ``).
DB_PASSWORD_FILE: Specify user's password to use to authenticate to the database via file input (alternative to DB_PASSWORD).
```

It might be I a nice option for the db.cert one too.

**Comment by lmsurpre** [comment] 2021-02-23 23:06
> DB_DB2_TENANT_KEY: [true/false]
Is tenant.key really true/false?  I thought that this property was a way for end users to request a specific tenant key (i.e. set to some specific string).
It really only makes sense if we're trying to support bootstrapping of a db2 schema.  In that scenario your really do need to pass this value up-front because you also need to set this same value in the fhir-server-config.json (which I assume the end user will still need to provide...we discussed automating the configDropin datasources but not really the corresponding entries in fhir-server-config.json).

Aside:  the DB_DB2_ prefix felt a bit redundant.  Having the common DB_ prefix is nice, but this one could maybe just be DB2_TENANT_KEY.  I guess it could be argued either way though.

**Comment by prb112** [comment] 2021-02-24 00:04
As an aside, the fhir-persistence-schema now should be excluded from the pom.xml of the fhir-server-webapp. 
And added locally.  

If bootstrap.sh is going to take on the behavior of setting up every db, I think that's a design discussion we should have. 
I think we should focus on Derby only in this issue.

**Comment by tbieste** [comment] 2021-02-24 15:13
> > DB_DB2_TENANT_KEY: [true/false]
> 
> Is tenant.key really true/false? I thought that this property was a way for end users to request a specific tenant key (i.e. set to some specific string).
> It really only makes sense if we're trying to support bootstrapping of a db2 schema. In that scenario you really do need to pass this value up-front because you also need to set this same value in the fhir-server-config.json (which I assume the end user will still need to provide...we discussed automating the configDropin datasources but not really the corresponding entries in fhir-server-config.json).
> 
> Aside: the DB_DB2_ prefix felt a bit redundant. Having the common DB_ prefix is nice, but this one could maybe just be DB2_TENANT_KEY. I guess it could be argued either way though.
I just made a copy/paste error on this one.  Yeah, it wasn't supposed to be true/false.

**Comment by tbieste** [comment] 2021-02-24 15:17
Focusing only on Derby would be nice, even just to keep things simpler with the deadline to finish this.

**Comment by punktilious** [comment] 2021-03-02 19:24
In FHIRServerContextListener:
private void safeRollback(UserTransaction tx)

no longer used.

**Comment by punktilious** [comment] 2021-03-02 19:27
Removing in my workspace so it gets pushed in whatever I commit next.

**Closed** 2021-03-10 16:06 UTC
Labels: P2, performance
