### ISSUE TITLE
Delete non-existing resource should not return 404

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#171] opened 2019-09-30 20:47 UTC
Test the delete operation of a non-existent resource instance. The expected response is either a 200 (OK) with an optional OperationOutcome in JSON format or 204 (No Content) and the content is empty; 

https://touchstone.aegis.net/touchstone/scriptexecution?exec=201909301514297516767573&qn=/FHIR4-0-0-Advanced/Patient/05-delete/fhir-api-r4-patient-delete-01-base#WAITING_OPER

**Comment by lmsurpre** [comment] 2019-10-01 02:22
I'm not convinced this expected behavior is right.

For example, see the convo at https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Conditional.20delete.200.20matches.20case

I think we should open a GForge to get clarity in the spec.

**Comment by lmsurpre** [comment] 2019-10-01 02:35
OK, I take it back, that convo is wrt conditional delete.  Spec is pretty clear that a delete of a non-existent resource should be a 200 or 204:

https://www.hl7.org/fhir/http.html#delete
> Upon successful deletion, or if the resource does not exist at all, the server should return either a 200 OK if the response contains a payload, or a 204 No Content with no response payload, or a 202 Accepted if the server wishes to be non-commital about the outcome of the delete.

**Comment by lmsurpre** [comment] 2019-10-01 02:46
Actually, since #118 was never closed...lets just use that one to address this.
Duplicate of #118

**Closed by lmsurpre** 2019-10-01 02:46 UTC
