### ISSUE TITLE
Throw an exception when a value set include filter cannot be applied or a concept filter cannot be created

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2163] opened 2021-03-28 02:38 UTC
In `GraphTermServiceProvider` and `CodeSystem` we currently log a warning when a value set include filter cannot be applied or a concept filter cannot be created. A better approach would be to throw a `FHIRTermException` and/or a `FHIRTermServiceException`. One issue that I ran into with throwing an exception is something I found in the spec artifacts:
https://chat.fhir.org/#narrow/stream/179202-terminology/topic/ValueSet.20with.20is-not-a.20filter.20refers.20to.20a.20CodeSystem.20that.20do

**Comment by lmsurpre** [comment] 2021-03-29 14:03
Discussed this one with John a bit and we think that we can add special case logic to handle `IS-A` and `IS-NOT-A` like an identity filter in cases where hierarchyMeaning is not defined.

**Comment by JohnTimm** [comment] 2021-03-29 14:09
The special case logic would also be required for `GENERALIZES`.

**Comment by lmsurpre** [comment] 2021-04-12 03:50
@JohnTimm is this one done?

**Comment by lmsurpre** [comment] 2021-04-12 17:02
John confirmed that this should be under QA because the corresponding change has already been merged.

**Comment by lmsurpre** [comment] 2021-04-12 17:26
During QA I found that our valueset-expand operation doesn't support input parameters at this time (as expected) and that, when passed, it leads to a 500 server error.  I think we should change that to a 4xx error with an OperationOutcome.issue of "not-supported" (which is currently mapped to a 400 bad request error at this time).

**Comment by lmsurpre** [comment] 2021-04-12 18:21
I posted the following to https://localhost:9443/fhir-server/api/v4/ValueSet/$expand
```
{
    "resourceType": "ValueSet",
    "id": "test",
    "url": "http://ibm.com/fhir/ValueSet/test",
    "version": "1",
    "name": "Test ValueSet",
    "status": "active",
    "compose": {
        "include": [
            {
                "system": "http://ibm.com/fhir/CodeSystem/test",
                "filter": [
                    {
                        "property": "concept",
                        "op": "regex",
                        "value": "a"
                    }
                ]
            }
        ]
    }
}
```

The result was a 400 bad request:
```
{
    "resourceType": "OperationOutcome",
    "id": "7f-0-0-1-8d5ecb1f-699e-454f-83b8-0b502ff3c68e",
    "issue": [
        {
            "severity": "error",
            "code": "not-supported",
            "details": {
                "text": "RegexFilter not created (property: concept, op: regex, value: a)"
            }
        }
    ]
}
```

This part seems to be working as desired.

**Comment by lmsurpre** [comment] 2021-04-12 19:39
> Sample request that was failing: https://localhost:9443/fhir-server/api/v4/ValueSet/test/$expand?filter=Concept (where the test ValueSet exists).

Confirmed that, with the latest change, this one now returns a 400 Bad Request with a body like the following:
```
{
    "resourceType": "OperationOutcome",
    "id": "7f-0-0-1-c84acefa-349b-4e05-b3d9-ee7a22dc90ea",
    "issue": [
        {
            "severity": "fatal",
            "code": "not-supported",
            "details": {
                "text": "Expansion parameters are not supported"
            },
            "expression": [
                "<empty>"
            ]
        }
    ]
}
```

**Closed by lmsurpre** 2021-04-12 19:39 UTC
Labels: terminology
