### ISSUE TITLE
X-FHIR-FORWARDED-URL not correct with bulk data

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2126] opened 2021-03-22 18:06 UTC
**Describe the bug**
Passing in a header X-FHIR-FORWARD-URL=https://myUrl.com/context/root/$export on a bulk data export results in the result header of content-location to equal https://myUrl.com/context/root/$export/$bulkdata-status?...
**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by lmsurpre** [comment] 2021-03-22 18:23
I *wasn't* able to reproduce this from the latest in main:
![image](https://user-images.githubusercontent.com/5478798/112039086-0426e300-8b1a-11eb-89a6-cf3306d40413.png)

I'm suggesting we close it unless we can reproduce.

**Comment by prb112** [comment] 2021-03-22 18:41
I'm not able to reproduce either. 

I need to see the request/curl and the fhir-server-config.json. 
Please ping me the details, and we can debug

**Comment by prb112** [comment] 2021-03-22 18:52
Also look for this in your logs... `Error while computing the original request URI`

**Comment by prb112** [comment] 2021-03-22 19:37
It's the body that won't output in the polling of the status

**Comment by prb112** [comment] 2021-03-22 20:46
Worked with Dag on this.

**Comment by prb112** [comment] 2021-03-22 23:52
Addressed issue in one on one consultation. 
Dag found three issues total, one was related to the URL passed in which caused the above fix.  
We've made it a bit more resilient in the PR. Moving to QA

**Comment by lmsurpre** [comment] 2021-03-24 14:00
Confirmed with Dag that this is working.

**Closed** 2021-03-24 14:00 UTC
Labels: bug
