### ISSUE TITLE
[fhir-client] Calling $validate from the fhir-client fails in the main branch

### ISSUE THREAD

**Issue by vikforfda** [IBM/FHIR#3722] opened 2022-06-17 18:15 UTC
We are using the FHIRClient validate method to validate Bundle resource by passing the Bundle object. 

client.validate(finalBundle)

It fails to perform validation. The FHIR server log displays following message

[6/17/22, 16:27:24:361 UTC] 00000042 FHIRHttpServl 2   Creating FHIRHttpServletRequestWrapper for HttpServletRequest: [com.ibm.ws](http://com.ibm.ws/).webcontainer40.srt.SRTServletRequest40@ee864739
[6/17/22, 16:27:24:361 UTC] 00000042 FHIRHttpServl 2   Retrieved these 'header' query parameters from the request URI: {}
[6/17/22, 16:27:24:361 UTC] 00000042 FHIRHttpServl 2   Content-Type is application/xml
[6/17/22, 16:27:24:361 UTC] 00000042 FHIRRestServl I   Received request: tenantId:[default] dsId:[default] user:[fhiruser] method:[POST] uri:[http://ibm-fhir.dev.splfhirpoc.com/fhir-server/api/v4/Resource/$validate]
[6/17/22, 16:27:24:365 UTC] 00000042 FHIRProvider  > com.ibm.fhir.provider.FHIRProvider readFrom ENTRY
[6/17/22, 16:27:24:375 UTC] 00000042 FHIRProvider  < com.ibm.fhir.provider.FHIRProvider readFrom RETURN
[6/17/22, 16:27:24:376 UTC] 00000042 Operation     > com.ibm.fhir.server.resources.Operation invoke(String,String,Resource) ENTRY
[6/17/22, 16:27:24:376 UTC] 00000042 FHIRResource  1   'Resource' is not a valid resource type.
[6/17/22, 16:27:24:381 UTC] 00000042 FHIRResource  1
OperationOutcome:
{"resourceType":"OperationOutcome","id":"ac-13-0-2-cd77fa72-e66c-4b97-a533-56c7af817a67","issue":[{"severity":"fatal","code":"not-supported","_code":{"extension":[{"url":"http://ibm.com/fhir/extension/not-supported-detail","valueCode":"resource"}]},"details":{"text":"'Resource' is not a valid resource type."}}]}
[6/17/22, 16:27:24:381 UTC] 00000042 RestAuditLogg > com.ibm.fhir.server.util.RestAuditLogger logOperation ENTRY
[6/17/22, 16:27:24:381 UTC] 00000042 RestAuditLogg < com.ibm.fhir.server.util.RestAuditLogger logOperation RETURN
[6/17/22, 16:27:24:381 UTC] 00000042 Operation     < com.ibm.fhir.server.resources.Operation invoke(String,String,Resource) RETURN
[6/17/22, 16:27:24:382 UTC] 00000042 FHIRProvider  > com.ibm.fhir.provider.FHIRProvider writeTo ENTRY
[6/17/22, 16:27:24:385 UTC] 00000042 FHIRProvider  < com.ibm.fhir.provider.FHIRProvider writeTo RETURN
[6/17/22, 16:27:24:385 UTC] 00000042 FHIRRestServl I   Completed request[0.024226862 secs]: tenantId:[default] dsId:[default] user:[fhiruser] method:[POST] uri:[http://ibm-fhir.dev.splfhirpoc.com/fhir-server/api/v4/Resource/$validate] status:[404]
[6/17/22, 16:27:24:385 UTC] 00000042 FHIRRestServl < com.ibm.fhir.server.filter.rest.FHIRRestServletFilter doFilter RETURN

**Following is a sample Bundl resource that has validation error but the validation operation does npt detect it**
[EST-REG-ForVikas-RegTesting-Enriched.xml.zip](https://github.com/IBM/FHIR/files/8929771/EST-REG-ForVikas-RegTesting-Enriched.xml.zip)

**Comment by lmsurpre** [comment] 2022-06-17 18:51
Thanks Vikas.  It looks like the client was dependent on $validate being served at `[base]/Resource/$validate`.
We used to support that but I removed that support in #3265.
I think we'll need to update the client to infer the resource type from the resource that was passed.

https://chat.fhir.org/#narrow/stream/179166-implementers/topic/.24validate.20operation.20url for more info.

**Comment by lmsurpre** [comment] 2022-06-20 14:20
@vikforfda what kind of object is your `finalBundle`?

our FHIRClientImpl validate implementation is already invoking validate on a type-specific basis, and so I now suspect this is an issue with your code and not ours.

**Comment by lmsurpre** [comment] 2022-06-20 14:32
closing as unable to reproduce

**Closed by lmsurpre** 2022-06-20 14:32 UTC
Labels: bug

**Comment by vikforfda** [comment] 2022-06-22 15:25
The issue was on our side. We were using an older version of fhir client to invoke the validation operation API. After we updated it to use versions 4.11.1 (most recent IBM-FHIR release) or 5.0.0-SNAPSHOT (corresponds to the WIP IBM-FHIR R4b release) then the validation correctly identified the error
