### ISSUE TITLE
Search based on Date with the Procedure resource is not working

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#1294] opened 2020-06-29 15:26 UTC
**Describe the bug**
This search does not find any resources, but there are resources that fall within this date range
 {
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "searchQuery",
            "valueString": "Procedure?patient=Patient/xxxx&date=gt2010-03-23T23:00:00.000Z&date=lt2020-06-27T23:00:00.000Z&_count=500"
        }
   ]

**To Reproduce**
create a Procedure resource linked to a patient where the performedDateTime is set to a timestamp of last year linked to patient "A".
Using the search above with Patient "A" reference.  Issue the search.
No results found. 
**Expected behavior**
The Search range should find the resource based on the date search. as the performedDateTime is within the date range.

**Additional context**

**Comment by prb112** [comment] 2020-06-29 17:20
Please provide example data to reproduce.

**Comment by d0roppe** [comment] 2020-06-29 18:23
This Procedure is not found with the above search.  Patient being the same
{
                        "fullUrl": "https://localhost:9443/fhir-server/api/v4/Procedure/xxxx",
                        "resource": {
                            "resourceType": "Procedure",
                            "id": "xxxx",
                            "meta": {
                                "versionId": "1",
                                "lastUpdated": "2020-06-27T02:41:13.388Z",
                                "profile": [
                                    "http://ibm.com/fhir/pdm/StructureDefinition/pdm-general-procedure-profile|1.0.0"
                                ],
                                "tag": [
                                    {
                                        "system": "http://ibm.com/watson-health-wpd/pdm/app-id",
                                        "code": "PERF1"
                                    },
                                    {
                                        "system": "http://ibm.com/watson-health-wpd/pdm/latest-app-id",
                                        "code": "PERF1"
                                    },
                                    {
                                        "system": "http://ibm.com/watson-health-wpd/pdm/data-type",
                                        "code": "primary"
                                    },
                                    {
                                        "system": "http://ibm.com/watson-health-wpd/pdm/request-id",
                                        "code": "b3062a1b-ed04-44a1-ad0b-508fc0f75f09"
                                    }
                                ]
                            },
                            "text": {
                                "status": "additional",
                                "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Testing is what us Minions do!</div>"
                            },
                            "status": "not-done",
                            "code": {
                                "coding": [
                                    {
                                        "system": "http://snomed.info/sct",
                                        "code": "115006"
                                    }
                                ]
                            },
                            "subject": {
                                "reference": "Patient/xxxx"
                            },
                            "performedDateTime": "2019-06-08T12:23:56.789Z"
                        }

**Comment by punktilious** [comment] 2020-06-29 18:59
The lastUpdated time will be the server time when the resource was stored, not the value given in the resource payload. The upper range on the filter predicate needs to take this into account.

**Comment by prb112** [comment] 2020-06-29 19:16
> The lastUpdated time will be the server time when the resource was stored, not the value given in the resource payload. The upper range on the filter predicate needs to take this into account.

The issue is a profile based problem. 

@d0roppe I can only replicate this when I have us-core enabled
`us-core-procedure-date` 
[http://hl7.org/fhir/us/core/SearchParameter/us-core-procedure-date](http://hl7.org/fhir/us/core/SearchParameter/us-core-procedure-date)

The Search Parameter overrides the Procedure SearchParameter code 'date'.
```
	"code": "date",
	"base": ["Procedure"],
	"type": "date",
	"expression": "Procedure.occurrence",
	"xpath": "f:Procedure/f:occurrenceDateTime",
```

Please confirm your userlib has the us-core library.

**Comment by prb112** [comment] 2020-06-29 19:26
John confirmed you are using it.  We have three actions: 

1 - Confirm a workaround
2 - Raise a temporary fix to our us-core copy 
3 - Open an HL7 FHIR Tracker

**Comment by prb112** [comment] 2020-06-29 19:30
Opened Tracker Item - https://jira.hl7.org/browse/FHIR-27887

**Comment by prb112** [comment] 2020-06-29 19:58
To work around the issue Per #1 above you need to add an extension-search-parameter for your tenant. 

[extension-search-parameters.json.txt](https://github.com/IBM/FHIR/files/4847733/extension-search-parameters.json.txt)
*Converted back to json file.

**Comment by prb112** [comment] 2020-07-01 20:51
Code is merged

**Closed** 2020-07-01 20:51 UTC
Labels: bug
