### ISSUE TITLE
The validation service requires a "snapshot" property in the StructureDefinition which is not required in HL7 spec

### ISSUE THREAD

**Issue by nicovn** [IBM/FHIR#2829] opened 2021-10-04 15:37 UTC
The validation service throws an error when the StructureDefinition profile does not contain a "snapshot" property.

According to "http://www.hl7.org/fhir/structuredefinition.html" the "snapshot" property has a cardinality of "0..1" (so not required)

**Environment**
IBM FHIR Server 4.9.0

Example:

https://simplifier.net/eHealthPlatformFederalProfiles/BePatient/~json

**Comment by JohnTimm** [comment] 2021-10-04 15:41
This is by design. Although the specification does _not_ require a snapshot, our constraint generation mechanism does. I believe that there are tools out there to generate a snapshot from a differential.

**Comment by nicovn** [comment] 2021-10-05 07:37
Hi John,

Thanks for the feedback.

Sushi (https://fshschool.org/docs/sushi/running/) has indeed an option (-s) to generate a snapshot representation

Best Regards

Nico

**Comment by prb112** [comment] 2021-10-07 19:13
Merged - let us know if you need anything else

**Closed by prb112** 2021-10-07 19:13 UTC
Labels: bug
